### PR TITLE
markdown-preview-added

### PR DESCRIPTION
**Pull request by ganesharulanantham**
**Issue:**  markdown preview https://github.com/getfider/fider/issues/544

To preview the markdown text input given by user in new idea description, comment and welcome message. Created a new React component wrapping Text area and Markdown Preview. 
Example Screenshot
screenshot 2018-10-11 at 12 03 29 am
screenshot 2018-10-11 at 12 03 35 am

### CODE REVIEW

**Comment by goenning** [comment]
I have a few comments, hope you don't mind!

I have just removed `semantic-ui-react`, this has been a very long process and I finally merged the last PR. This has dropped the css from 172 KiB to 114 KiB, and the js from 378 KiB to only 105 KiB! I'm sorry, but we won't be able to use Tabs component from that package 😣

We can either create our own basic Tab component or choose another design, like this:

What do you think? I think it looks cleaner and we already have the Toggle component (it could be much smaller though...)

screenshot 2018-10-10 at 20 50 53

**Comment by ganesharulanantham** [comment]
@goenning got it. will first try to implement our own tab implementation. It fits for all pages as text area   and then will try toggle. Toggle also sounds like a good idea.

**Comment by goenning** [comment]
I kind of liked the Toggle more than Tabs, mostly because it uses less space and there's nothing between the input and the textarea. I'm afraid that the "Write" + "Preview" floating text might make users confused.

**Comment by goenning** [comment]
Hmm, that’s actually a good point. Well, give it a try and let’s see how it looks like. Thst one one is not frequently used, as it’s only visible to staff users. I’d prefer one that fits better on the home/comment screen.

**Pull request closed without merging**
