### PR TITLE
Add .nvmrc

### PR DESCRIPTION
**Pull request by ashishmohite**
-  improves build reproducibility by switching to an appropriate node version

### CODE REVIEW

**Comment by goenning** [comment]
Thanks for your contribution. I like the idea of having a .nvmrc as some use it a lot, although I’m not a big fan of adding it as a dependency to the contributing. The less tool we require, the less friction it creates for new contributors to join.

**Comment by ashishmohite** [comment]
@goenning can I add optional in parenthesis in front of the requirement? or should just remove it from the requirements ?

**Comment by goenning** [comment]
I’d prefer to revert that file and add a note beside the Node.js requirement, something like:

- Node.js 10+ (https://nodejs.org/ or run `nvm use` if you have nvm)

What you think?

**Comment by ashishmohite** [comment]
Done

**Comment by goenning** [comment]
@ashishmohite merged. Thanks! 😀

**Pull request merged**
