### PR TITLE
Fix: Healthcheck errors if Host Domain set

### PR DESCRIPTION
**Pull request by gerkevgarderen**
Updated Ping command to fix health check errors

**Issue:** https://github.com/getfider/fider/issues/1047

When Host Domain is set, the Docker health check used to return errors.
This PR fixes that issue and also adds support for health checks if the app is running on ports other than the default 3000.

### CODE REVIEW

**Comment by goenning** [comment]
Ahh, we’re using a custom cmd for health check, I thought it was curl, so maybe that’s why it didn’t work.

the problem with this solution is that by sending a request to the actual domain, it’ll go through the internet instead of being a local request. So if the container is healthy but somewhere up the stack there is a problem, the health check will fail.

can you try adding a “Host” header to the http request? Curious to see if that’d work

**Comment by gerkevgarderen** [comment]
> the problem with this solution is that by sending a request to the actual hostname, it’ll go through the internet instead of being a local request. So if the container is healthy but somewhere up the stack there is a problem, the health check will fail.

Yes, that's a fair point!

> can you try adding a “Host” header to the http request? Curious to see if that’d work

Sadly this does not work, for reference see the last commit.
I tried to test more in-depth by installing cURL in a running Fider container. Same result, the error originating from:
https://github.com/getfider/fider/blob/f9eed164d39fb865ce119753706e601827f7a204/app/middlewares/security.go#L22

Looking a bit more into that line, it seems the hostame in that check is originating from the actual Request URL. If I understand correctly, allowing the Host header to override this might mean allowing a bypass of this security measure.

Perhaps we can exempt the _health endpoint from the check? Not the most elegant solution but I believe this would not pose any significant risk as that endpoint does not send or process any information.

**Comment by gerkevgarderen** [comment]
For reference, here's what I did for testing curl from inside the container:
- Start shell in container: `docker exec -it <FIDER_CONTAINER_NAME> /bin/bash`
- Install curl: `apt install curl`
- Run request with Host (also tested host for sanity):
  `curl localhost:3000/_health -H Host=<HOST_DOMAIN>`
- Try request with a resolve IP override:
  `curl --resolve <HOST_DOMAIN>:*:127.0.0.1 -I <HOST_DOMAIN>/_health`

**Comment by goenning** [comment]
Thanks for the investigation above, I tried this `curl localhost:3000/_health -H Host=<HOST_DOMAIN>` and it also didn't work, but apparently the syntax is `-H "Host: value`, so when I tried:

`curl -k https://localhost:3000/_health -H "Host: <HOST_DOMAIN>"` I got 200 OK with `{}` response. So that worked in curl, but not in go.

So after some digging I found this https://github.com/golang/go/issues/29865

instead of `req.Header.Set("Host", env.Config.HostDomain)`, it has to be `req.Host = env.Config.HostDomain`.

---

> Looking a bit more into that line, it seems the hostame in that check is originating from the actual Request URL. If I understand correctly, allowing the Host header to override this might mean allowing a bypass of this security measure.

We had attacks before where requests where coming in as `https://{IP}/send-invite -H "Host: maliciousdomain.com`, before this check, we would accept the request and the `c.Request.URL.Hostname` was `maliciousdomain.com`. So every time we used that variable to build a URL and send by email, we were sending a hijacked url.

That's where this protection was introduced, if you override the Host header to a value that is different than what's configure, you get a 404.

**Comment by goenning** [comment]
If that works for you too, we can merge this. By the way, good catch on the PORT, didn't notice we had it hardcoded :)

**Comment by gerkevgarderen** [comment]
Ah, so both attempts to use the Host header were incorrect, sorry about that 😅 thanks for taking the time to investigate it too!

I haven't worked much with Go before so I thought checking with curl would help me ensure it wasn't my code but that didn't quite work out, haha.
I'll test your solution tomorrow and update the PR.

> That's where this protection was introduced, if you override the Host header to a value that is different than what's configure, you get a 404.

Ah okay, that makes sense. With your solution it seems we won't have to touch it, but this helps me to understand the setup better :)

Thanks for the fast response & engaging in finding the solution.

**Comment by gerkevgarderen** [comment]
Just tested your fix, this works perfectly for our instance 👌

I have updated the PR with the fix, should be ready to merge.

**Comment by goenning** [comment]
@gerkevgarderen thank you! 🚀

**Pull request merged**
