### PR TITLE
feat: add webhook

### PR DESCRIPTION
**Pull request by acamilleri**
**Issues:**  
- https://github.com/getfider/fider/issues/892
- related https://github.com/getfider/fider/issues/882

### CODE REVIEW

**Comment by acamilleri** [comment]
@goenning Available for help me to debug test ? it's very strange ...

**Comment by acamilleri** [comment]
Up @goenning please :)

**Comment by mipapo** [comment]
Looks good to me. 
If relevant, it would be interesting to be able to configure not only one webhook URL and to add the webhook addresses - except for special adjustments such as for Slack in the database?

**Comment by acamilleri** [comment]
> Looks good to me.
> If relevant, it would be interesting to be able to configure not only one webhook URL and to add the webhook addresses - except for special adjustments such as for Slack in the database?

I think it can be possible to configure webhooks in the admin interface with a lot of changes, but it needs a lot of work.

I don't open Fider since this PR, i will try to find a lot of time to work on it ASAP.

**Comment by goenning** [comment]
closing this due to a more configurable solution  #980

**Pull request closed without merging**
