### PR TITLE
Format Typescript with Prettier

### LINKED ISSUE #309: add Prettier and ensure there's no issues during CI/CD run
https://basarat.gitbooks.io/typescript/content/docs/tools/prettier.html

### PR DESCRIPTION
**Pull request by LukeSheard**
Close #309 by using [tslint-config-prettier](http://npm.im/tslint-config-prettier) and [tslint-plugin-prettier](http://npm.im/tslint-plugin-prettier) to lint code formatting.

### CODE REVIEW

**Comment by goenning** [comment]
@LukeSheard Thanks for the contribution, looks great! I'll review it sometime this week. 

Any idea what's the most common settings for TypeScript/React, single or double quotes? I decided to go with single because that's what react uses, but I'm happy with whatever is the "standard".

**Comment by LukeSheard** [comment]
@goenning I just normally go for the default, but bump up the print-width a little because I find 80 just a little too thin. Although I think it's really just project preference, most I've seen normally do something similar to me.

**Comment by goenning** [comment]
I'm not familiar with Prettier, but I pulled this PR locally and tried to run `make lint`. Output is:

```
npx tslint -c tslint.json 'public/**/*.{ts,tsx}'
Error: Comment location overlaps with node location
    at decorateComment (/Users/goenning/Documents/workspace/go-workspace/src/github.com/getfider/fider/node_modules/prettier/index.js:7992:11)
    at decorateComment (/Users/goenning/Documents/workspace/go-workspace/src/github.com/getfider/fider/node_modules/prettier/index.js:7967:7)
    at decorateComment (/Users/goenning/Documents/workspace/go-workspace/src/github.com/getfider/fider/node_modules/prettier/index.js:7967:7)
    at decorateComment (/Users/goenning/Documents/workspace/go-workspace/src/github.com/getfider/fider/node_modules/prettier/index.js:7967:7)
    at decorateComment (/Users/goenning/Documents/workspace/go-workspace/src/github.com/getfider/fider/node_modules/prettier/index.js:7967:7)
    at decorateComment (/Users/goenning/Documents/workspace/go-workspace/src/github.com/getfider/fider/node_modules/prettier/index.js:7967:7)
    at decorateComment (/Users/goenning/Documents/workspace/go-workspace/src/github.com/getfider/fider/node_modules/prettier/index.js:7967:7)
    at decorateComment (/Users/goenning/Documents/workspace/go-workspace/src/github.com/getfider/fider/node_modules/prettier/index.js:7967:7)
    at decorateComment (/Users/goenning/Documents/workspace/go-workspace/src/github.com/getfider/fider/node_modules/prettier/index.js:7967:7)
    at decorateComment (/Users/goenning/Documents/workspace/go-workspace/src/github.com/getfider/fider/node_modules/prettier/index.js:7967:7)
    at decorateComment (/Users/goenning/Documents/workspace/go-workspace/src/github.com/getfider/fider/node_modules/prettier/index.js:7967:7)
    at decorateComment (/Users/goenning/Documents/workspace/go-workspace/src/github.com/getfider/fider/node_modules/prettier/index.js:7967:7)
    at decorateComment (/Users/goenning/Documents/workspace/go-workspace/src/github.com/getfider/fider/node_modules/prettier/index.js:7967:7)
    at decorateComment (/Users/goenning/Documents/workspace/go-workspace/src/github.com/getfider/fider/node_modules/prettier/index.js:7967:7)
    at decorateComment (/Users/goenning/Documents/workspace/go-workspace/src/github.com/getfider/fider/node_modules/prettier/index.js:7967:7)
    at comments.forEach (/Users/goenning/Documents/workspace/go-workspace/src/github.com/getfider/fider/node_modules/prettier/index.js:8048:5)
```

Any idea what is this? I guess we'd see same issue on CircleCI if it had run. I misconfigured something, but if you push a new commit it should trigger the build now.

Another thing is, can you revert the last commit with the badge? I'd rather not add more badges at the moment.

**Comment by LukeSheard** [comment]
@goenning I've removed the badge and added a workaround the error you see (https://github.com/prettier/prettier/issues/2347#issuecomment-324060291)

**Comment by goenning** [comment]
@LukeSheard Thanks for the contribution, that was great! 👍

**Pull request merged**
