### PR TITLE
Before running mage task, check whether dependencies are installed

### PR DESCRIPTION
**Pull request by nclandrei**
**Issue: #590**  

Before running any Mage task, there will be an OS agnostic check to see whether all dependencies are correctly installed.

### CODE REVIEW

**Comment by goenning** [comment]
> Hey, @goenning! I submitted the pull request and, funnily enough, one of the dependencies (i.e. air) is missing from the CircleCI build environment, so building the PR fails 😁 I propose that air is also installed on CircleCI as this would be the desired environment (i.e. all the required dependencies should be installed on the build env as well). What do you think?

Nice! So that means it's working as expected! 😁

I have installed air on that Build image, you'll need to change the `.circleci/config.yml` to use `getfider/circleci:0.0.15` instead of `0.0.14`, can you do that? That version should have air installed.

I'd also suggest that we put a link to the CONTRIBUTING.md whenever the missing dependencies fail. This might help them on how to install the missing dependencies. Maybe on a new line after that message:

To learn how, visit our contributors guide: https://github.com/getfider/fider/blob/master/CONTRIBUTING.md

**Comment by goenning** [comment]
> Hey, @goenning! I submitted the pull request and, funnily enough, one of the dependencies (i.e. air) is missing from the CircleCI build environment, so building the PR fails 😁 I propose that air is also installed on CircleCI as this would be the desired environment (i.e. all the required dependencies should be installed on the build env as well). What do you think?

Nice! So that means it's working as expected! 😁

I have installed air on that Build image, you'll need to change the `.circleci/config.yml` to use `getfider/circleci:0.0.15` instead of `0.0.14`, can you do that? That version should have air installed.

I'd also suggest that we put a link to the CONTRIBUTING.md whenever the missing dependencies fail. This might help them on how to install the missing dependencies. Maybe on a new line after that message:

To learn how, visit our contributors guide: https://github.com/getfider/fider/blob/master/CONTRIBUTING.md

**Comment by goenning** [comment]
> Hey, @goenning! I submitted the pull request and, funnily enough, one of the dependencies (i.e. air) is missing from the CircleCI build environment, so building the PR fails 😁 I propose that air is also installed on CircleCI as this would be the desired environment (i.e. all the required dependencies should be installed on the build env as well). What do you think?

Nice! So that means it's working as expected! 😁

I have installed air on that Build image, you'll need to change the `.circleci/config.yml` to use `getfider/circleci:0.0.15` instead of `0.0.14`, can you do that? That version should have air installed.

I'd also suggest that we put a link to the CONTRIBUTING.md whenever the missing dependencies fail. This might help them on how to install the missing dependencies. Maybe on a new line after that message:

To learn how, visit our contributors guide: https://github.com/getfider/fider/blob/master/CONTRIBUTING.md

One last thing, I'd move the missingDependencies function to the bottom of that file, together with other "Utils" functions that we might have there.

**Comment by goenning** [comment]
> Hey, @goenning! I submitted the pull request and, funnily enough, one of the dependencies (i.e. air) is missing from the CircleCI build environment, so building the PR fails 😁 I propose that air is also installed on CircleCI as this would be the desired environment (i.e. all the required dependencies should be installed on the build env as well). What do you think?

Nice! So that means it's working as expected! 😁

I have installed air on that Build image, you'll need to change the `.circleci/config.yml` to use `getfider/circleci:0.0.15` instead of `0.0.14`, can you do that? That version should have air installed.

I'd also suggest that we put a link to the CONTRIBUTING.md whenever the missing dependencies fail. This might help them on how to install the missing dependencies. Maybe on a new line after that message:

To learn how, visit our contributors guide: https://github.com/getfider/fider/blob/master/CONTRIBUTING.md

One last thing, I'd move the missingDependencies function to the bottom of that file, together with other "Utils" functions that we might have there.

**Comment by nclandrei** [comment]
Sounds great! On it! 🙂

**Pull request merged**
