### PR TITLE
refactor: Migrate Select component to functional component using useState hook

### PR DESCRIPTION
**Pull request by npham49**
**Issue:** https://github.com/getfider/fider/issues/730

**Description of changes:**
- Refactored form/Select component to funcitonal component
- Kept all the original functionality and jsx code

**Question:**
- When working on this, my terminal threw an error: ```invalid go version '1.22.0': must match format 1.23``` which required me to change the go.mod to 1.22, let me know if I need to change it back and how I can fix this error!

### CODE REVIEW

**Comment by mattwoberts** [comment]
@npham49 Awesome thanks. 

There is an issue with the go version though. It fails to build on my (Apple Silicon) mac:

```bash
go build -ldflags '-s -w -X github.com/getfider/fider/app/pkg/env.commithash=' -o fider .
go: downloading go1.22 (darwin/arm64)
go: download go1.22 for darwin/arm64: toolchain not available
make: *** [build-server] Error 1
```

Looking at https://github.com/golang/go/issues/62278#issuecomment-1693538776 and it seems to be that a specific version is needed for a toolchain to be used, so I need to change to `1.22.0` in order for it to work on my machine.

**Comment by npham49** [comment]
> @npham49 Awesome thanks.
> 
> There is an issue with the go version though. It fails to build on my (Apple Silicon) mac:
> 
> ```shell
> go build -ldflags '-s -w -X github.com/getfider/fider/app/pkg/env.commithash=' -o fider .
> go: downloading go1.22 (darwin/arm64)
> go: download go1.22 for darwin/arm64: toolchain not available
> make: *** [build-server] Error 1
> ```
> 
> Looking at [golang/go#62278 (comment)](https://github.com/golang/go/issues/62278#issuecomment-1693538776) and it seems to be that a specific version is needed for a toolchain to be used, so I need to change to `1.22.0` in order for it to work on my machine.

Thanks for having a look at this so fast! I think this might be a problem with the go setup on my end then, I'll go ahead and fix my setup, and then push another commit changing it back to ```1.22.0```.

**Comment by mattwoberts** [comment]
Cool. I'm just curious - what motivated you to pick this up? Strange question i know but I'm still finding my feet with it myself so the more i ask the better 👍

**Comment by npham49** [comment]
For this specific issue? I was just going through the "help wanted" items, and working on the ones that I can do. I'm pretty new to Go (this project is literally my first-time using Go), but I've been working with React professionally for a couple years now, so these React tickets are more straight-forward for me.

Also, congratulations on being the new owners! Fider was used in my previous company, and we loved how easy and intuitive it was for end user to log feedback.

**Comment by mattwoberts** [comment]
Ah I see, thanks :) I was curious why you picked fider to contribute to - so that makes sense that you knew of it from using it.

Thanks for the kind words - we're hoping to add some nice features to fider and boost the customer count over at fider.io - all of which should benefit the self hosters :)

**Comment by npham49** [comment]
@mattwoberts it's an awesome piece of software! Let me know if you need help with any of the new features/bug fixes (tag me in any issues or whichever project board you're using), I'm more than happy to contribute to make fider even better.

**Pull request merged**
