### PR TITLE
fix: Allow SMTP without StartTLS

### PR DESCRIPTION
**Pull request by gs11**
Fixes https://github.com/getfider/fider/issues/925

Disclaimer, I've not written a single line of Go so I'm very open to improvement suggestions (if any) 😅 
Tested OK in local setup.

### CODE REVIEW

**Comment by goenning** [comment]
Code looks good to me! I’d just suggest naming it `..._ENABLE_STARTTLS` and make it true by default. It’s often easier to read code with positive variables instead of negating a negative var

**Comment by gs11** [comment]
Changed as suggested @goenning

**Comment by goenning** [comment]
@gs11 thanks for your contribution. Did you have any issues when setting up Fider locally? I’m trying to simplify where possible, so any feedback is appreciated.

**Comment by gs11** [comment]
Thanks!
No issues really but minor hurdles:
* Required `pg_trgm` extension disallowed us to use our internal shared DB cluster
* Undocumented environment variables (such as `SIGNUP_DISABLED`)

Other than that, very smooth experience with great docs!

**Pull request merged**
